from numpy.typing import NDArray
import numpy as np
from collections import defaultdict
from dipoleska.utils.inference import InferenceMixin
from dipoleska.utils.posterior import PosteriorMixin
from dipoleska.models.model_helpers import LikelihoodMixin, MapModelMixin
from dipoleska.models.priors import Prior
from dipoleska.utils.math import compute_multipole_signal

class Multipole(LikelihoodMixin, InferenceMixin, MapModelMixin, PosteriorMixin):
    def __init__(self,
            density_map: NDArray[np.int_ | np.float64],
            ells: list[int],
            prior: Prior | None = None, 
    ):
        '''
        nice.
        '''
        self._get_healpy_map_attributes(density_map)
        self._construct_multipole_priors(ells, prior)
        
        # if we are fitting a monopole (ell=0), adjust the monopole prior to center
        # around the mean number density; otherwise, for point-by-point, the
        # prior will automatically lack a monopole prior, so no change needed
        if any(ell == 0 for ell in ells):
            self.monopole_is_fitted = True
            self._parse_likelihood_choice('poisson')
        else:
            self.monopole_is_fitted = False

        self._parameter_names = self.prior.parameter_names
        self.ndim = self.prior.ndim
        self.n_multipoles = len(ells)
        self._get_angle_indices()
    
    def _construct_multipole_priors(self,
            ells: list[int],
            prior: Prior | None = None
    ) -> None:
        if prior is None:
            azimuthal_priors = ['Uniform', 0., 2 * np.pi]
            polar_priors = ['Polar', 0., np.pi]
            amplitude_priors = ['Uniform', 0., 0.1]
            monopole_priors = ['Uniform', 0., 0.] # placeholder: is replaced later
            all_amplitude_priors = {}
            all_angle_priors = {}
            
            for ell in ells:    
                if ell == 0:
                    label = 'M0'
                    all_amplitude_priors[label] = monopole_priors
                
                else:
                    amplitude_label = f'M{ell}'
                    prior_list = amplitude_priors.copy()
                    prior_list[-1] = prior_list[-1] * ell ** 2 # naively scale prior range by ell^2
                    all_amplitude_priors[amplitude_label] = prior_list

                    # for each ell with amplitude M_ell, add the 2*ell unit vector priors
                    for i in range(2 * ell):
                        subscript = f'l{ell}_{i//2}'

                        if i % 2 == 0:
                            all_angle_priors[f'phi_{subscript}'] = azimuthal_priors
                        else:
                            all_angle_priors[f'theta_{subscript}'] = polar_priors
            
            all_priors = {**all_amplitude_priors, **all_angle_priors}
            self._prior = Prior(choose_prior=all_priors)
        else:
            self._prior = prior

    def _get_angle_indices(self):
        self.phi_indices = defaultdict(list)
        self.theta_indices = defaultdict(list)
        
        for i, key in enumerate(self.parameter_names):
            if 'M' in key:
                continue
            else:
                angle_type, ell, vec_number = key.split('_') # e.g. phi_l2_1

                new_key = f'{ell[1:]}'

                if angle_type == 'phi':
                    self.phi_indices[new_key].append(i)
                else:
                    self.theta_indices[new_key].append(i)

    def _parse_multipole_likelihood(self, ells: list[int]) -> None:
        pass

    @property
    def density_map(self) -> NDArray[np.int_ | np.float64]:
        '''
        Whenever the model calls the `density_map` attribute, provide only the
        unmasked pixels for inference.
        '''
        return self._density_map[self.boolean_mask]
    
    @property
    def pixel_vectors(self) -> NDArray[np.float64]:
        '''
        Whenever the model calls the `pixel_vectors` attribute, provide only
        the vectors pointing to unmasked pixels.
        '''
        return self._pixel_vectors[self.boolean_mask]
    
    @property
    def pixel_vectors_xyz(self) -> list[NDArray[np.float64]]:
        x, y, z = self.pixel_vectors.T
        return [x, y, z]

    @property
    def prior(self) -> Prior:
        return self._prior
    
    @property
    def parameter_names(self) -> list[str]:
        return self._parameter_names
    
    def log_likelihood(self,
            Theta: NDArray[np.float64]
    ) -> NDArray[np.float64]:
        '''
        Log likelihood function passed to the Nested Sampler. Automatically
        adjusted depending on whether or not the user is fitting a monopole by
        passing ell = [0, ...] at instantiation.

        :param Theta: Parameter samples from the prior distribtuion, as
            generated by the Nested Sampler.
        '''
        multipole_terms = self.model(Theta)

        if self.monopole_is_fitted:
            return self.poisson_log_likelihood(
                rate_parameter=multipole_terms,
                density_map=self.density_map
            )
        else:
            return self.point_by_point_log_likelihood(
                multipole_signal=multipole_terms,
                density_map=self.density_map
            )
    
    def model(self, Theta: NDArray[np.float64]) -> NDArray[np.float64]:
        '''
        The essential idea of to iterate over each ell, computing the multipole
        signal for that particular order. For example, if a user specifies
        `ells = [1,2,3]`, we compute the dipole signal, then the quadrupole
        signal, then the octupole signal, summing them cumulatively.
        '''
        nlive = Theta.shape[0]
        if self.monopole_is_fitted: # exclude first params, which will be Nbar
            amplitude_like = Theta[:, 1:self.n_multipoles]
        else:
            amplitude_like = Theta[:, :self.n_multipoles]
        
        signal = np.ones((self.n_unmasked, nlive))
        for i, ((ell, phi_idxs), (ell, theta_idxs)) in enumerate(
            zip(self.phi_indices.items(), self.theta_indices.items())
        ):
            signal += compute_multipole_signal(
                multipole_amplitudes=amplitude_like[:, i],
                multipole_longitudes=Theta[:, phi_idxs],
                multipole_latitudes=Theta[:, theta_idxs],
                pixel_vectors=self.pixel_vectors_xyz
            ) # shape?
        
        if self.monopole_is_fitted:
            mean_number_density = Theta[:, 0]
            return mean_number_density[None, :] * np.ones(signal.shape) * signal
        else:
            return signal